server.port: 8081
spring:
  application.name: monitor
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/database/monitor-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
    password: 123
  h2:
    console:
      enabled: true
      # Permite acesso remoto
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Alterar para create-drop em caso de mudanca do schema
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: algasensors-rabbitmq
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener:
      simple:
        prefetch: 4
        retry:
          enabled: true
          initial-interval: 10s
          max-interval: 30s
          multiplier: 2
#          max-attempts: 3 its the default

logging:
  level:
    root: INFO
    lutz.algasensors: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/monitor.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
